### ISSUE TITLE
Key to :set paste

### ISSUE THREAD

**Issue by thobianchi** [jessfraz/.vim#7]
[Here](https://github.com/jfrazelle/.vim/blob/master/vimrc#L232-242) I see that some shortcut is created to send `:set paste`.  
I can't find out what is it, maybe my keymap is a bit different with yours so I'm in the dark.
By the way this repo is very cool, thanks!!!!!

**Comment by jfrazelle** [comment]
So I got this from @soulshake :) https://gist.github.com/soulshake/5f37713e470cb53a6fab






On Thu, Dec 10, 2015 at 8:25 AM -0800, "Thomas Bianchi" <notifications@github.com> wrote:












Here I see that some shortcut is created to send :set paste.


I can't find out what is it, maybe my keymap is a bit different with yours so I'm in the dark.

By the way this repo is very cool, thanks!!!!!

**Comment by mintyc** [comment]
Any chance you could update the auto paste code to adapt to vim use inside tmux?
The gist refs the original script url which has an updated escaped tmux compatible variant. Maybe ref the original post instead?

**Comment by veggiemonk** [comment]
@mintyc I think you mean this? https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode

**Comment by rmariano** [comment]
Hi, this might be of some help. I used to have a custom function for ``:set paste``, but afterwards I found a builtin setting. Checkout https://github.com/rmariano/vim-config/commit/f485ebe05bbfc77b1c896e1b065d7fdc0aac370d

Just my 2 cents, hope it helps 😄

**Comment by jessfraz** [comment]
closing as this works for me but feel free to discuss :) thanks!
